# Generated by Django 4.2.7 on 2025-06-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_category_slug'),
        ('LittleLemonAPI', '0003_remove_orderitem_price_remove_orderitem_unit_price_and_more'),
    ]

    operations = [
    ]
